"""
Django settings for Fantasy_Dreams project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
# from neomodel import config


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '87t=v$l%k*t&plq2lc3jb$q(2!=!80o&i!+-9k#!f_mf^*^@lz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'mainpage.apps.MainpageConfig',
    'chat.apps.Neo4JConfig',
    'aposta.apps.ApostaConfig',
    'esportes.apps.EsportesConfig',
    'jogadores.apps.JogadoresConfig',
    'partidas.apps.PartidasConfig',
    'times.apps.TimesConfig',
    'torneios.apps.TorneiosConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Fantasy_Dreams.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Fantasy_Dreams.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'FantasyDreams',
        'USER': 'postgres',
        'PASSWORD': 'ri19981234',
        'HOST': 'localhost',
        'PORT': '5432',
    },

    'mongoDB': {
        'ENGINE': 'djongo',
        'NAME': 'FantasyStarMongo',
        'USER': 'mongo',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '27017',
    },

    'neo4j' : {
        'HOST':'localhost',
        'NAME':'Chat',
        'neo4j': 'neo4j',
        'PASSWORD':'123',
        'PORT':7687,
        'ENDPOINT':'/db/data'
    }
}

# Neo4j database
# config.DATABASE_URL = 'bolt://localhost:7687'
# config.ENCRYPTED_CONNECTION  = False
# config.DATABASE_USER = 'neo4j'
# os.environ.DATABASE_PASSWORD = '123'
# NEO4J_PASSWORD='123'


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
