# Generated by Django 3.0.7 on 2020-07-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aposta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopremium',
            name='projeto_id',
        ),
    ]
